import { PHI, PHI_SQRT, phiPow, SCALE_STEPS, fmt } from './phi'

// Token generators: each function takes a base unit and produces
// a self-contained file a designer can drop into any project.
// The generated output includes comments explaining every value,
// so it's useful even outside this playground.

export function generateCSSTokens(baseUnit: number): string {
  const lines: string[] = [
    '/* ═══════════════════════════════════════════════════════════',
    ' * φ Design Tokens — Golden Ratio CSS Custom Properties',
    ` * Base unit: ${baseUnit}rem`,
    ` * φ (phi): ${fmt(PHI)}`,
    ' * Generated by φ Grid — https://phi-grid.dev',
    ' * ═══════════════════════════════════════════════════════════ */',
    '',
    ':root {',
    `  --phi: ${fmt(PHI)};`,
    `  --phi-base: ${baseUnit}rem;`,
    '',
    '  /* ── Spacing Scale ─────────────────────────────────────── */',
  ]

  for (const step of SCALE_STEPS) {
    const value = baseUnit * phiPow(step.exp)
    const comment = `/* ${step.formula} = ${fmt(value)}rem */`
    lines.push(`  --sp-${step.name}: ${fmt(value)}rem;  ${comment}`)
  }

  lines.push('')
  lines.push('  /* ── Font Size Scale ──────────────────────────────────── */')

  const fsSizes = [
    { name: 'xs',  exp: -1,   formula: 'φ⁻¹' },
    { name: 'sm',  exp: -0.5, formula: 'φ⁻⁰·⁵' },
    { name: 'md',  exp: 0,    formula: 'φ⁰' },
    { name: 'lg',  exp: 0.5,  formula: '√φ' },
    { name: 'xl',  exp: 1,    formula: 'φ¹' },
    { name: '2xl', exp: 1.5,  formula: 'φ¹·⁵' },
    { name: '3xl', exp: 2,    formula: 'φ²' },
    { name: '4xl', exp: 3,    formula: 'φ³' },
  ]

  for (const fs of fsSizes) {
    const value = baseUnit * phiPow(fs.exp)
    lines.push(`  --fs-${fs.name}: ${fmt(value)}rem;  /* ${fs.formula} */`)
  }

  lines.push('')
  lines.push('  /* ── Line Heights ────────────────────────────────────── */')
  lines.push(`  --lh-tight: 1.236;   /* 1 + (φ−1)² */`)
  lines.push(`  --lh-base: ${fmt(PHI)};    /* φ */`)
  lines.push(`  --lh-loose: ${fmt(Math.pow(PHI, 1.5))};   /* φ¹·⁵ */`)

  lines.push('')
  lines.push('  /* ── Letter Spacing ──────────────────────────────────── */')
  lines.push('  --ls-tight: -0.02em;')
  lines.push('  --ls-base: 0em;')
  lines.push(`  --ls-wide: ${fmt(phiPow(-3))}em;  /* φ⁻³ */`)

  lines.push('')
  lines.push('  /* ── Border Radius ───────────────────────────────────── */')
  const spXs = baseUnit * phiPow(-2)
  const spSqrt = baseUnit * PHI_SQRT
  const spLg = baseUnit * PHI
  lines.push(`  --radius-sm: ${fmt(spXs)}rem;  /* sp-xs */`)
  lines.push(`  --radius-md: ${fmt(spSqrt)}rem;  /* sp-sqrt = √φ */`)
  lines.push(`  --radius-lg: ${fmt(spLg)}rem;  /* sp-lg = φ¹ */`)
  lines.push('  --radius-pill: 999px;')

  lines.push('')
  lines.push('  /* ── Breakpoints (φ-derived) ─────────────────────────── */')
  const bpSm = Math.round(320 * PHI)
  const bpMd = Math.round(bpSm * PHI)
  const bpLg = Math.round(bpMd * PHI)
  lines.push(`  --bp-sm: ${bpSm}px;  /* 320 × φ */`)
  lines.push(`  --bp-md: ${bpMd}px;  /* ${bpSm} × φ */`)
  lines.push(`  --bp-lg: ${bpLg}px;  /* ${bpMd} × φ */`)

  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Generate SCSS variables + CSS custom properties.
 */
export function generateSCSSTokens(baseUnit: number): string {
  const lines: string[] = [
    '// ═══════════════════════════════════════════════════════════',
    '// φ Design Tokens — Golden Ratio SCSS Variables',
    `// Base unit: ${baseUnit}rem`,
    `// φ (phi): ${fmt(PHI)}`,
    '// Generated by φ Grid — https://phi-grid.dev',
    '// ═══════════════════════════════════════════════════════════',
    '',
    `$phi: ${fmt(PHI)};`,
    `$phi-base: ${baseUnit}rem;`,
    '',
    '// ── Spacing Scale ──────────────────────────────────────────',
  ]

  for (const step of SCALE_STEPS) {
    const value = baseUnit * phiPow(step.exp)
    lines.push(`$sp-${step.name}: ${fmt(value)}rem;  // ${step.formula}`)
  }

  lines.push('')
  lines.push('// ── Font Size Scale ─────────────────────────────────────')

  const fsSizes = [
    { name: 'xs', exp: -1 },
    { name: 'sm', exp: -0.5 },
    { name: 'md', exp: 0 },
    { name: 'lg', exp: 0.5 },
    { name: 'xl', exp: 1 },
    { name: '2xl', exp: 1.5 },
    { name: '3xl', exp: 2 },
    { name: '4xl', exp: 3 },
  ]

  for (const fs of fsSizes) {
    const value = baseUnit * phiPow(fs.exp)
    lines.push(`$fs-${fs.name}: ${fmt(value)}rem;`)
  }

  lines.push('')
  lines.push('// ── Line Heights ─────────────────────────────────────────')
  lines.push('$lh-tight: 1.236;')
  lines.push(`$lh-base: ${fmt(PHI)};`)
  lines.push(`$lh-loose: ${fmt(Math.pow(PHI, 1.5))};`)

  lines.push('')
  lines.push('// ── Border Radius ────────────────────────────────────────')
  lines.push(`$radius-sm: $sp-xs;`)
  lines.push(`$radius-md: $sp-sqrt;`)
  lines.push(`$radius-lg: $sp-lg;`)
  lines.push('$radius-pill: 999px;')

  lines.push('')
  lines.push('// ── CSS Custom Properties (include in your :root) ───────')
  lines.push(':root {')
  lines.push('  --phi: #{$phi};')
  lines.push('  --phi-base: #{$phi-base};')
  lines.push('')

  for (const step of SCALE_STEPS) {
    lines.push(`  --sp-${step.name}: #{$sp-${step.name}};`)
  }
  lines.push('')
  for (const fs of fsSizes) {
    lines.push(`  --fs-${fs.name}: #{$fs-${fs.name}};`)
  }
  lines.push('')
  lines.push('  --lh-tight: #{$lh-tight};')
  lines.push('  --lh-base: #{$lh-base};')
  lines.push('  --lh-loose: #{$lh-loose};')
  lines.push('')
  lines.push('  --radius-sm: #{$radius-sm};')
  lines.push('  --radius-md: #{$radius-md};')
  lines.push('  --radius-lg: #{$radius-lg};')
  lines.push('  --radius-pill: #{$radius-pill};')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Generate JS/TS constants file.
 */
export function generateJSTokens(baseUnit: number): string {
  const lines: string[] = [
    '/**',
    ' * φ Design Tokens — Golden Ratio Constants',
    ` * Base unit: ${baseUnit}rem`,
    ` * φ (phi): ${fmt(PHI)}`,
    ' * Generated by φ Grid — https://phi-grid.dev',
    ' */',
    '',
    `export const PHI = ${PHI};`,
    `export const PHI_BASE = ${baseUnit};`,
    '',
    '// Spacing scale (rem)',
    'export const spacing = {',
  ]

  for (const step of SCALE_STEPS) {
    const value = baseUnit * phiPow(step.exp)
    lines.push(`  '${step.name}': ${fmt(value)},  // ${step.formula}`)
  }
  lines.push('} as const;')

  lines.push('')
  lines.push('// Font sizes (rem)')
  lines.push('export const fontSize = {')

  const fsSizes = [
    { name: 'xs', exp: -1 },
    { name: 'sm', exp: -0.5 },
    { name: 'md', exp: 0 },
    { name: 'lg', exp: 0.5 },
    { name: 'xl', exp: 1 },
    { name: '2xl', exp: 1.5 },
    { name: '3xl', exp: 2 },
    { name: '4xl', exp: 3 },
  ]

  for (const fs of fsSizes) {
    const value = baseUnit * phiPow(fs.exp)
    lines.push(`  '${fs.name}': ${fmt(value)},`)
  }
  lines.push('} as const;')

  lines.push('')
  lines.push('// Line heights')
  lines.push('export const lineHeight = {')
  lines.push('  tight: 1.236,')
  lines.push(`  base: ${fmt(PHI)},`)
  lines.push(`  loose: ${fmt(Math.pow(PHI, 1.5))},`)
  lines.push('} as const;')
  lines.push('')

  return lines.join('\n')
}

// Browser download trick: create a Blob URL, click a hidden <a>, then clean up.
// No server round-trip needed — everything is generated client-side.
export function downloadFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
